name: Deploy site
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.147.0"

      - name: Build site
        run: hugo --minify

      - name: Configure Git
        run: |
          git config --global user.name "artyvr"
          git config --global user.email "immitto@gmail.com"

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v4
        with:
           deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
           external_repository: artyvr/artyvr.github.io
           publish_dir: ./public
           keep_files: false
           cname: artyvr.ru