name: Deploy site

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.147.0"

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
           github_tokens: ${{ secrets.GH_PAT }}
           external_repository: artyvr/artyvr.github.io
           publish_branch: gh-pages
           publish_dir: ./
           keep_files: false
           cname: artyvr.ru

